import re
import sys

def strip_signature_lines(stub_path: str) -> None:
    # Matches a default generated type docstring generated by stubgen, which is not useful to us.
    default_type_docstring_pattern = re.compile(
        r'(?<=:)[ \t\f\v]*\n[ \t\f\v]*"""IcePy(\.\w+)+"""',
        re.MULTILINE
    )
    # Matches a leading line inside a docstring that looks like a function signature.
    function_signature_pattern = re.compile(
        r'(?<=""")[ \t\f\v]*\w+\(.*?\)(?:[ \t\f\v]*->[ \t\f\v]*[\w\[\],|. ]+)?[ \t\f\v]*(?:\n|(?="""))[\s\n]*',
        re.MULTILINE
    )
    # Matches any empty doc-strings left behind after removing the function signatures.
    empty_docstring_pattern = re.compile(r'(?<=:)\s*[ \t\f\v]*"""[ \t\f\v]*"""[ \t\f\v]*')
    # Matches one of the default '__init__' function generated by stubgen, which is not useful to us.
    init_function_pattern_1 = re.compile(
        r'''
    \@classmethod
    def __init__\(cls, \*args, \*\*kwargs\) -> None:
        """Create and return a new object\.  See help\(type\) for accurate signature\."""''',
        re.MULTILINE
    )
    # Matches the other default '__init__' function generated by stubgen, which is also not useful to us.
    init_function_pattern_2 = re.compile(
        r'''
    def __init__\(self, \*args, \*\*kwargs\) -> None:
        """Initialize self.  See help\(type\(self\)\) for accurate signature\."""''',
        re.MULTILINE
    )

    # Read the content of the file into a string.
    with open(stub_path, "r") as f:
        content = f.read()

    # Process the doc-strings by stripping out anything generated by stubgen that we don't want.
    content = default_type_docstring_pattern.sub("", content)
    content = function_signature_pattern.sub("", content)
    content = empty_docstring_pattern.sub(" ...", content)
    content = init_function_pattern_1.sub("", content)
    content = init_function_pattern_2.sub("", content)

    # Write the sanitized content back to the file.
    with open(stub_path, "w") as f:
        f.write(content)

if __name__ == "__main__":
    for path in sys.argv[1:]:
        strip_signature_lines(path)
        print(f"Processed: {path}")
