//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.8.0-alpha.0
//
// <auto-generated>
//
// Generated from file `BuiltinSequences.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __BuiltinSequences_h__
#define __BuiltinSequences_h__

#include <Ice/PushDisableWarnings.h>
#include <Ice/Config.h>
#include <Ice/ObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ValueF.h>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30850
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

namespace Ice
{
    /**
     * A sequence of bools.
     */
    using BoolSeq = ::std::vector<bool>;

    /**
     * A sequence of bytes.
     */
    using ByteSeq = ::std::vector<std::byte>;

    /**
     * A sequence of shorts.
     */
    using ShortSeq = ::std::vector<::std::int16_t>;

    /**
     * A sequence of ints.
     */
    using IntSeq = ::std::vector<::std::int32_t>;

    /**
     * A sequence of longs.
     */
    using LongSeq = ::std::vector<::std::int64_t>;

    /**
     * A sequence of floats.
     */
    using FloatSeq = ::std::vector<float>;

    /**
     * A sequence of doubles.
     */
    using DoubleSeq = ::std::vector<double>;

    /**
     * A sequence of strings.
     */
    using StringSeq = ::std::vector<::std::string>;

    /**
     * A sequence of objects.
     */
    using ObjectSeq = ::std::vector<ValuePtr>;

    /**
     * A sequence of object proxies.
     */
    using ObjectProxySeq = ::std::vector<::std::optional<::Ice::ObjectPrx>>;

}

#include <Ice/PopDisableWarnings.h>
#endif
