//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.8.0-alpha.0
//
// <auto-generated>
//
// Generated from file `PropertyDict.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __PropertyDict_h__
#define __PropertyDict_h__

#include <Ice/PushDisableWarnings.h>
#include <Ice/Config.h>
#include <map>
#include <string>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30850
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

namespace Ice
{
    /// A simple collection of properties, represented as a dictionary of key/value pairs. Both key and value are
    /// strings.
    /// @see PropertiesAdmin#getPropertiesForPrefix
    using PropertyDict = ::std::map<::std::string, ::std::string>;

}

#include <Ice/PopDisableWarnings.h>
#endif
