//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.8.0-alpha.0
//
// <auto-generated>
//
// Generated from file `SliceChecksumDict.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __SliceChecksumDict_h__
#define __SliceChecksumDict_h__

#include <Ice/PushDisableWarnings.h>
#include <Ice/Ice.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30850
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

namespace Ice
{
    /// Mapping from type IDs to Slice checksums. The dictionary allows verification at run time that client and server
    /// use matching Slice definitions. Ice 3.8 no longer generates Slice checksums but we keep the dictionary definition
    /// for backward compatibility.
    using SliceChecksumDict = ::std::map<::std::string, ::std::string>;

}

#include <Ice/PopDisableWarnings.h>
#endif
